### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by erichuang2015** [rioncarter/whois-caching-proxy#1]
Hello

I am a starter  for golang , I have my go env setup well on centos 7, how can I install this script in my system ?

**Comment by boredwookie** [comment]
I've updated the readme to include the following notes:
- Go 1.11 (or higher) is required to build the project
- Check out the repo with git clone
- cd into the repo directory and run `go build`

**Comment by rioncarter** [comment]
I've updated the readme to include the following notes:

- Go 1.11 (or higher) is required to build the project
- Check out the repo with git clone
- cd into the repo directory and run `go build`
